import { Check, Copy, Crown, KeyRound, UsersRound } from 'lucide-react';
import { useState } from 'react';
import { useAuth } from '../contexts/AuthContext';
import { useData } from '../contexts/DataContext';
import UserAvatar from '../components/UserAvatar';
import { groupForUser } from '../utils/app';
import { makeId } from '../utils/security';

export default function GroupPage() {
  const { user } = useAuth(); const { data, commit, addNotification } = useData(); const [code, setCode] = useState(''); const [message, setMessage] = useState(''); const [copied, setCopied] = useState(false);
  const group = groupForUser(user, data.groups);
  const request = data.joinRequests.find((item) => item.userId === user.uid && item.status === 'pending');
  const join = (event) => { event.preventDefault(); setMessage(''); const found = data.groups.find((item) => item.code.toLowerCase() === code.trim().toLowerCase()); if (!found) return setMessage('No active discussion group uses that code.'); if (request) return setMessage('You already have a pending group request.'); const created = { id: makeId('join'), userId: user.uid, groupId: found.id, status: 'pending', createdAt: new Date().toISOString() }; commit((current) => ({ ...current, joinRequests: [...current.joinRequests, created] })); [...found.dglIds, ...data.users.filter((item) => item.role === 'admin').map((item) => item.uid)].forEach((uid) => addNotification({ userId: uid, title: 'New group join request', message: `${user.fullName} requested to join ${found.name}.` })); setMessage(`Your request to join ${found.name} was sent.`); };
  if (!group) return <div className="join-group-page"><div className="empty-state empty-state--large"><UsersRound /><h1>You are not in a discussion group yet.</h1><p>Enter the code given by your DGL. Your request must be approved before you are added.</p>{request && <div className="form-alert"><Check size={18} /> A group request is currently pending.</div>}<form className="join-code-form" onSubmit={join}><KeyRound /><input value={code} onChange={(e) => setCode(e.target.value.toUpperCase())} placeholder="Enter group code" disabled={Boolean(request)} required /><button className="button" disabled={Boolean(request)}>Request to join</button></form>{message && <div className="form-alert">{message}</div>}</div></div>;
  const members = data.users.filter((item) => item.groupId === group.id && item.accountStatus === 'approved');
  const copyCode = async () => { await navigator.clipboard?.writeText(group.code); setCopied(true); setTimeout(() => setCopied(false), 1500); };
  return <div className="page-stack"><section className="group-hero"><div className="group-hero__mark"><UsersRound /></div><div><span>YOUR DISCUSSION GROUP</span><h1>{group.name}</h1><p>{group.description || 'Growing together through honest conversations, prayer, and friendship.'}</p></div><div className="group-code"><small>GROUP CODE</small><strong>{group.code}</strong><button onClick={copyCode}>{copied ? <Check /> : <Copy />}{copied ? 'Copied' : 'Copy'}</button></div></section><div className="group-layout"><section className="group-main"><article className="content-card"><div className="content-card__heading"><div><span>GROUP MEMBERS</span><h2>People walking with you</h2></div><span className="chip">{members.length} members</span></div><div className="member-list">{members.map((member) => <div key={member.uid} className="member-row"><UserAvatar user={member} /><div><strong>{member.fullName}</strong><span>{member.role === 'dgl' ? 'Discussion Group Leader' : 'Participant'}</span></div>{group.dglIds.includes(member.uid) && <Crown size={17} />}<span className="member-status">Active</span></div>)}</div></article></section><aside className="group-aside"><article className="content-card"><span className="kicker">GROUP COVENANT</span><p className="covenant-text">What is shared in the group stays in the group. We listen without judgment, speak with kindness, and help one another encounter Christ.</p></article></aside></div></div>;
}
